### ISSUE TITLE
Bibtex plugin has hardcoded paths which cause errors

### ISSUE THREAD

**Issue by dkozel** [wolfv/uberwriter#19]
When building the head of master ( https://github.com/wolfv/uberwriter/commit/da4efb4b0b4f28006ee361e6887b67250e9fd706 ) I encounter the following error:

```
[dkozel@moscato uberwriter] python3 ./setup.py build
/home/dkozel/src/uberwriter/uberwriter/__init__.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk # pylint: disable=E0611
/home/dkozel/src/uberwriter/uberwriter/UberwriterWindow.py:30: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, WebKit, Gio  # pylint: disable=E0611
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 349, in __external_mod
    mod = __import__(module)
ImportError: No module named 'latexenc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dkozel/src/uberwriter/uberwriter/plugins/bibtex/gi_composites.py", line 254, in __call__
    template_bytes = Gio.resources_lookup_data(self.ui, Gio.ResourceLookupFlags.NONE)
GLib.Error: g-resource-error-quark: The resource at '/home/wolfv/Programs/uberwriter/uberwriter/plugins/bibtex/bibtex_item.glade' does not exist (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./setup.py", line 177, in <module>
    ('/usr/share/glib-2.0/schemas', ['data/glib-2.0/schemas/net.launchpad.uberwriter.gschema.xml'])
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 412, in __add_imports
    elif node.module and __external_mod(cur_module, node.module, attrs):
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 354, in __external_mod
    mod = __import__(cur_module + '.' + module)
  File "/home/dkozel/src/uberwriter/uberwriter/__init__.py", line 26, in <module>
    from . import UberwriterWindow
  File "/home/dkozel/src/uberwriter/uberwriter/UberwriterWindow.py", line 64, in <module>
    from .plugins.bibtex import BibTex
  File "/home/dkozel/src/uberwriter/uberwriter/plugins/bibtex/__init__.py", line 1, in <module>
    from .bibtex import BibTex
  File "/home/dkozel/src/uberwriter/uberwriter/plugins/bibtex/bibtex.py", line 10, in <module>
    class BibTexItem(Gtk.Box):
  File "/home/dkozel/src/uberwriter/uberwriter/plugins/bibtex/gi_composites.py", line 263, in __call__
    with open(ui, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wolfv/Programs/uberwriter/uberwriter/plugins/bibtex/bibtex_item.glade'
```
This appears to be caused by the hardcoded paths in the bibtex plugin. I've removed the plugin and am able to use Uberwriter. The GTK and WebKit version warnings I'll address in a different issue.

Do you know if the `ImportError: No module named 'latexenc'` error is a result of the bibtex plugin error?

**Comment by johnblommers** [comment]
Attempts to install Uberwriter on Raspbian Jesse are met with this same error. I attempted to fix this by editing the hard coded paths to point to the current location of the referenced files and so it installed. But Uberwriter won't run and crashes instead:

```
Traceback (most recent call last):
  File "/usr/local/bin/uberwriter", line 46, in <module>
    import uberwriter
  File "/usr/local/lib/python3.4/dist-packages/uberwriter/__init__.py", line 26, in <module>
    from . import UberwriterWindow
  File "/usr/local/lib/python3.4/dist-packages/uberwriter/UberwriterWindow.py", line 64, in <module>
    from .plugins.bibtex import BibTex
ImportError: No module named 'uberwriter.plugins'
```

**Comment by wolfv** [comment]
sorry guys, this is a late reply. this specific issue has been fixed (by removing/disabling the plugin). But overall uberwriter needs quite a bit of work. 

Contributions welcome :)
